### ISSUE TITLE
Date/Timepicker wrong Format

### ISSUE THREAD

**Issue by frag92** [Zaliyo/osticket-one#1]
Hi There,
after implementing the theme, ive noticed, that the date/timepicker results in a strange "doubled" format. 
I tried to update/upgrade the Jquery-ui etc but nothing worked.. maybe you have a hint on what i can do. 
<img width="1037" alt="Date-Timepicker" src="https://user-images.githubusercontent.com/90747969/134128624-c6723e40-c0e9-47ea-9bae-203969da6426.PNG">
ed

**Comment by RHITNL** [comment]
> Hi There, after implementing the theme, ive noticed, that the date/timepicker results in a strange "doubled" format. I tried to update/upgrade the Jquery-ui etc but nothing worked.. maybe you have a hint on what i can do. <img alt="Date-Timepicker" width="1037" src="https://user-images.githubusercontent.com/90747969/134128624-c6723e40-c0e9-47ea-9bae-203969da6426.PNG"> ed

Hi there,

I've tried several places where the datepicker is available and it all looks good on my install with this theme.
![image](https://user-images.githubusercontent.com/6173448/135764067-ac4bee65-7858-42d8-a8ce-0478d38629a4.png)

Might have something to do with your browser?
On which screen does it appear? I don't recognize the screen you added.

**Comment by yayas87** [comment]
Unable to replicate this issue
